#!/bin/bash
if [ -r $HOME/.bash_aliases ]; then
  source $HOME/.bash_aliases
fi

if [ -r $HOME/Work/work-tools/workrc ]; then
  source $HOME/Work/work-tools/workrc
fi

if [ -r $HOME/.auth ]; then
  source $HOME/.auth
fi

# -------------------------------
# ENVIRONMENT CONFIGURATION
# -------------------------------
# export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
# export PATH="/usr/local/sbin/:$PATH"
# export PATH="~/.aws/aws-cli/:$PATH"
# export BASH_SILENCE_DEPRECATION_WARNING=1

# For compilers to find python@3.8
# export LDFLAGS="-L/usr/local/opt/python@3.8/lib"

# For pkg-config to find python@3.8
# export PKG_CONFIG_PATH="/usr/local/opt/python@3.8/lib/pkgconfig"

# Set Paths
# ------------------------------------------------------------
# export PATH="$PATH:/usr/local/bin/"
# export PATH="/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:$PATH"

# [ -f ~/.fzf.bash ] && source ~/.fzf.bash
[ -z "$ZSH_NAME" ] && [ -f ~/.fzf.bash ] && source ~/.fzf.bash
